DROP TABLE IF EXISTS SUPPORTER;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS USER;

 CREATE TABLE USER (
	ID BINARY(16),
	NAME VARCHAR(40),
	EMAIL VARCHAR(40),
	TELNO INT(20),
	PRIMARY KEY (ID)
 );

 CREATE TABLE PROJECT (
	ID BINARY(16),
	TITLE VARCHAR(50),
	DESCRIPTION VARCHAR(255),
	TARGETFIGURE INT(16) CHECK(TARGETFIGURE BETWEEN 0 AND 100000000),
	SUPPORTCOUNT INT(16) CHECK(SUPPORTCOUNT BETWEEN 0 AND 100000),
	SUPPORTAMOUNT INT(16) CHECK(SUPPORTAMOUNT BETWEEN 0 AND 100000000),
	STATE VARCHAR(10),
	ISOPEN BOOLEAN DEFAULT TRUE,
	CREATORID BINARY(16),
	STARTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ENDDATE TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (CREATORID) REFERENCES USER (ID)
 );

 CREATE TABLE SUPPORTER (
 	ID BINARY(16),
	AMOUNT INT(16),
	PROJECTID BINARY(16),
	USERID BINARY(16),
 	REGISTRATIONDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFICATIONDATE TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECTID) REFERENCES PROJECT (ID),
	FOREIGN KEY (USERID) REFERENCES USER (ID)
 );